package org.mama.funckydude;

import javax.swing.*;
import java.awt.*;

public class MainForm extends JFrame {
    private JPanel mainPanel;
    private JPanel tablePanel;
    private JList listTraders;
    private JTable tableGoods;
    private JScrollPane scrollGoods;
    private JScrollPane scrollTraders;
    private JLabel labelTextUrt;
    private JLabel labelGoods;
    private JLabel labelUrl;
    private JLabel labelTraders;
    private JButton addTraderButton;
    private JButton delTraderButton;
    private JButton delGoodButton;

    public MainForm() {
        super("Продавцы");
        setContentPane(mainPanel);

        JMenuBar mb = new JMenuBar();
        JMenu m1 = new JMenu("Операции");
        JMenu m2 = new JMenu("Помощь");
        mb.add(m1);
        mb.add(m2);

        JMenuItem menuLoadGoods = new JMenuItem("Все товары");
        JMenuItem menuLoadTraders = new JMenuItem("Загрузить продавца");
        JMenuItem menuSearch = new JMenuItem("Искать");
        JMenuItem menuExit = new JMenuItem("Выход");

        m1.add(menuLoadGoods);
        m1.add(menuLoadTraders);
        m1.add(menuSearch);
        m1.add(menuExit);

        mainPanel.add(BorderLayout.NORTH, mb);

        scrollGoods.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollGoods.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scrollTraders.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollTraders.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listTraders.setVisibleRowCount(5);
        listTraders.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        delGoodButton.addActionListener(e -> {
            long d = (long) tableGoods.getValueAt(tableGoods.getSelectedRow(), 0);
            MyStateManager.delGoods(d);
            Trader t = (Trader) listTraders.getSelectedValue();
            t.good.remove(d);
            tableGoods.setModel(new TraderTableModel(t));

        });

        addTraderButton.addActionListener(e -> {
            AddForm add = new AddForm();
            add.setBounds(700, 300, 300, 500);
            add.setVisible(true);
            add.listTraders.setModel(new TradersList(new MyStateManager()));
        });

        menuLoadTraders.addActionListener(e -> listTraders.setModel(new TradersList(new MyStateManager())));


        listTraders.addListSelectionListener(lse -> {
            if (!lse.getValueIsAdjusting()) {
                Trader t = (Trader) listTraders.getSelectedValue();
                labelTextUrt.setText(t.getUrl());
                tableGoods.setModel(new TraderTableModel(t));
            }
        });

        menuLoadGoods.addActionListener(e -> {
            try {
                tableGoods.setModel(new SimpleModel(new MyStateManager()));
            } catch (Exception ex) {
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        tablePanel = new JPanel();
        tablePanel.setLayout(new GridBagLayout());
        mainPanel.add(tablePanel, BorderLayout.CENTER);
        labelUrl = new JLabel();
        labelUrl.setText("URL");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        tablePanel.add(labelUrl, gbc);
        labelGoods = new JLabel();
        labelGoods.setText("Goods");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        tablePanel.add(labelGoods, gbc);
        labelTextUrt = new JLabel();
        labelTextUrt.setText(":");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        tablePanel.add(labelTextUrt, gbc);
        scrollGoods = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        tablePanel.add(scrollGoods, gbc);
        tableGoods = new JTable();
        scrollGoods.setViewportView(tableGoods);
        scrollTraders = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 3;
        gbc.fill = GridBagConstraints.BOTH;
        tablePanel.add(scrollTraders, gbc);
        listTraders = new JList();
        scrollTraders.setViewportView(listTraders);
        labelTraders = new JLabel();
        labelTraders.setBackground(new Color(-1912833));
        labelTraders.setText("Traders");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        tablePanel.add(labelTraders, gbc);
        addTraderButton = new JButton();
        addTraderButton.setText("Добавить");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        tablePanel.add(addTraderButton, gbc);
        delTraderButton = new JButton();
        delTraderButton.setText("Удалить");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        tablePanel.add(delTraderButton, gbc);
        delGoodButton = new JButton();
        delGoodButton.setText("Удалить");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        tablePanel.add(delGoodButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
