package org.mama.GoldenThought.SwingForms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.mama.GoldenThought.DAO.Entity.Word;
import org.mama.GoldenThought.WordHelper;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Vector;

public class MainForm extends JFrame {
    private JPanel mainPanel;
    private JPanel wordPanel;
    private JTable wordTable;
    private JScrollPane wordScroll;

    public MainForm() {
        super("Word's");
        setContentPane(mainPanel);

        Vector<Vector> data = new Vector<>();
        Vector<Word> word = new Vector<>(new WordHelper().getAllWords());

        for (Word w : word) {
            Vector row = new Vector();
            row.add(w.getName());
            data.add(row);
        }
        Vector<String> columns = new Vector<>();
        columns.add("Name");
        wordTable.setModel(new DefaultTableModel(data, columns));

        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        wordPanel = new JPanel();
        wordPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(wordPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        wordScroll = new JScrollPane();
        wordPanel.add(wordScroll, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        wordTable = new JTable();
        wordScroll.setViewportView(wordTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
