package lection;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainForm extends JFrame {
	private JPanel mainPanel;
	private JPanel bottomPanel;
	private JPanel gridPanel;
	private JButton searchButton;
	private JTextField searchField;
	private JScrollPane scrollPanel;
	private JTable table;

	public MainForm() {
		super("Прототип");
		$$$setupUI$$$();

		//Creating the MenuBar and adding components
		JMenuBar mb = new JMenuBar();
		JMenu m1 = new JMenu("Операции");
		JMenu m2 = new JMenu("Помощь");
		mb.add(m1);
		mb.add(m2);

		JMenuItem menuLoad = new JMenuItem("Загрузить");
		JMenuItem menuSearch = new JMenuItem("Искать");
		JMenuItem menuExit = new JMenuItem("Выход");

		m1.add(menuLoad);
		m1.add(menuSearch);
		m1.add(menuExit);

		scrollPanel.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		scrollPanel.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		mainPanel.add(BorderLayout.NORTH, mb);

		setContentPane(mainPanel);
		setVisible(true);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		menuLoad.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					table.setModel(JdbcAccess.getModel("Goods", null));
				} catch (Exception ex) {
				}
			}
		});

		searchButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					table.setModel(JdbcAccess.getModel("Goods", searchField.getText()));
				} catch (Exception ex) {
				}
			}
		});

		menuSearch.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					table.setModel(JdbcAccess.getModel("Goods", searchField.getText()));
				} catch (Exception ex) {
				}
			}
		});

		menuExit.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
				System.exit(0);
			}
		});
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new BorderLayout(0, 0));
		gridPanel = new JPanel();
		gridPanel.setLayout(new BorderLayout(0, 0));
		mainPanel.add(gridPanel, BorderLayout.CENTER);
		scrollPanel = new JScrollPane();
		gridPanel.add(scrollPanel, BorderLayout.CENTER);
		table = new JTable();
		scrollPanel.setViewportView(table);
		bottomPanel = new JPanel();
		bottomPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
		mainPanel.add(bottomPanel, BorderLayout.SOUTH);
		searchField = new JTextField();
		searchField.setHorizontalAlignment(2);
		searchField.setMinimumSize(new Dimension(60, 30));
		searchField.setPreferredSize(new Dimension(100, 30));
		searchField.setText("");
		bottomPanel.add(searchField);
		searchButton = new JButton();
		searchButton.setHorizontalAlignment(0);
		searchButton.setText("Искать");
		bottomPanel.add(searchButton);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
