package org.mama.secondProgect.SwingForms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.mama.secondProgect.DAO.Controls.TraderControl;
import org.mama.secondProgect.DAO.Entity.Trader;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddTraderForm extends JDialog {

    private JPanel mainPanel;
    private JTextField nameTraderField;
    private JTextField urlTraderField;
    private JTextField adressTraderField;
    private JLabel nameTrader;
    private JLabel urlName;
    private JLabel nameAdress;
    private JButton addTraderButton;

    public AddTraderForm(TraderControl traderControl, TraderForm traderForm) {
        super(traderForm, "Add trader", ModalityType.DOCUMENT_MODAL);
        setContentPane(mainPanel);
        setBounds(200, 200, 250, 250);

        addTraderButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!nameTraderField.getText().equals("")) {
                    Trader t = new Trader(nameTraderField.getText(), urlTraderField.getText(), adressTraderField.getText());
                    traderControl.insert(t);
                    traderForm.traders = traderControl.getArrayTraders();
                    traderForm.index = traderForm.traders.size() - 1;
                    traderForm.setAllOnForm(traderForm.index);
                } else {
                    nameTrader.setForeground(Color.RED);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        nameTrader = new JLabel();
        nameTrader.setText("Name");
        mainPanel.add(nameTrader, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        urlName = new JLabel();
        urlName.setText("URL");
        mainPanel.add(urlName, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameAdress = new JLabel();
        nameAdress.setText("Address");
        mainPanel.add(nameAdress, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTraderField = new JTextField();
        mainPanel.add(nameTraderField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(96, 30), null, 0, false));
        urlTraderField = new JTextField();
        mainPanel.add(urlTraderField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(96, 30), null, 0, false));
        adressTraderField = new JTextField();
        mainPanel.add(adressTraderField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(96, 30), null, 0, false));
        addTraderButton = new JButton();
        addTraderButton.setText("Add");
        mainPanel.add(addTraderButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
